name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Make patch script executable
        run: chmod +x patch.sh
      
      - name: Run patch script
        run: ./patch.sh
      
      - name: Upload golden-days-base artifacts
        uses: actions/upload-artifact@v4
        with:
          name: golden-days-base-latest-dev
          path: golden-days-base/*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: golden-days-alpha-latest-dev
          path: golden-days-alpha/*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: golden-days-shaders-latest-dev
          path: golden-days-shaders/*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: golden-days-classic-latest-dev
          path: golden-days-classic/*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: golden-days-better-foliage-latest-dev
          path: golden-days-better-foliage/*